language: cpp
env:
  - NODE_VERSION="0.10"
  - NODE_VERSION="0.12"
  - NODE_VERSION="4.4"
  - NODE_VERSION="5.9"
os:
  - osx
matrix:
  fast_finish: true
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm;
  - source /tmp/.nvm/nvm.sh;
  - nvm install $NODE_VERSION;
  - nvm use --delete-prefix $NODE_VERSION;
install:
  - npm install
script:
  - npm test
